#!/usr/bin/env python3
"""Continuous retraining pipeline — ground-station model improvement loop.

Ingests analyst feedback (corrected triage scores), fine-tunes the current
model, validates against a held-out set, and promotes only if metrics improve.

Designed to run on a ground station with a GPU. The resulting model is then
deployed to Jetson hardware via Docker image rebuild or model volume mount.

Workflow::

    Jetson (edge)        Ground station
    ─────────────        ──────────────
    1. Run inference  →  2. Downlink audit.jsonl
                         3. Analyst reviews decisions
                         4. This script: retrain + validate
                         5. Register improved model
    6. Deploy new model ←

Usage::

    # Retrain from analyst feedback CSV
    python scripts/retrain_pipeline.py --feedback data/feedback.csv

    # Retrain from audit log (pseudo-labels from triage decisions)
    python scripts/retrain_pipeline.py --from-audit logs/audit.jsonl

    # Dry run — train but don't register the model
    python scripts/retrain_pipeline.py --feedback data/feedback.csv --dry-run

    # Quick validation (1 epoch, small subset)
    python scripts/retrain_pipeline.py --feedback data/feedback.csv --quick

Feedback CSV format::

    tile_path,cloud_fraction,anomaly_score,value_score
    data/tiles/tile_001.npy,0.05,0.85,0.90
    data/tiles/tile_002.npy,0.92,0.10,0.15

Audit log JSON Lines (auto-generated by edge_triage.audit)::

    {"cnn_cloud_fraction":0.1,"cnn_anomaly_score":0.8,"cnn_value_score":0.9,...}
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
import time
from pathlib import Path

# ── Ensure project root is importable ───────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT / "src"))

import numpy as np

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
    from torch.utils.data import DataLoader, Dataset, random_split
except ImportError:
    sys.exit("ERROR: PyTorch required for retraining. Install with: pip install torch torchvision")

from edge_triage.model_registry import ModelRegistry

MODELS_DIR = PROJECT_ROOT / "models"


# ── Feedback dataset ────────────────────────────────────────────────────────


class FeedbackDataset(Dataset):
    """Dataset from analyst feedback CSV or audit log JSON Lines.

    Each sample is ``(tile_tensor, target_scores)`` where target_scores
    is ``[cloud_fraction, anomaly_score, value_score]``.
    """

    def __init__(self, tiles: list[np.ndarray], scores: list[tuple[float, float, float]]) -> None:
        assert len(tiles) == len(scores)
        self._tiles = tiles
        self._scores = scores

    def __len__(self) -> int:
        return len(self._tiles)

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        tile = torch.from_numpy(self._tiles[idx]).float()
        if tile.ndim == 2:
            tile = tile.unsqueeze(0)
        elif tile.ndim == 3 and tile.shape[-1] in (1, 3, 4, 13):
            tile = tile.permute(2, 0, 1)
        target = torch.tensor(self._scores[idx], dtype=torch.float32)
        return tile, target


def load_feedback_csv(path: Path) -> FeedbackDataset:
    """Load analyst-corrected scores from CSV.

    Expected columns: tile_path, cloud_fraction, anomaly_score, value_score
    """
    tiles: list[np.ndarray] = []
    scores: list[tuple[float, float, float]] = []

    with open(path, newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            tile_path = Path(row["tile_path"])
            if tile_path.suffix == ".npy":
                tile = np.load(str(tile_path), allow_pickle=False)
            else:
                from PIL import Image
                tile = np.array(Image.open(tile_path), dtype=np.float32)
                if tile.max() > 1.0:
                    tile = tile / 255.0

            tiles.append(tile)
            scores.append((
                float(row["cloud_fraction"]),
                float(row["anomaly_score"]),
                float(row["value_score"]),
            ))

    print(f"Loaded {len(tiles)} feedback samples from {path}")
    return FeedbackDataset(tiles, scores)


def load_audit_log(path: Path) -> FeedbackDataset:
    """Create pseudo-labeled dataset from audit log decisions.

    Uses the CNN scores from the audit log as training targets.
    This enables self-supervised improvement: the model learns from its own
    confident decisions, filtered by analyst-reviewed keep/filter choices.
    """
    tiles: list[np.ndarray] = []
    scores: list[tuple[float, float, float]] = []

    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            # Handle HMAC-appended lines (content\thmac)
            if "\t" in line:
                line = line.rsplit("\t", 1)[0]
            try:
                record = json.loads(line)
            except json.JSONDecodeError:
                continue

            # Extract CNN scores as pseudo-labels
            cloud = record.get("cnn_cloud_fraction", 0.5)
            anomaly = record.get("cnn_anomaly_score", 0.5)
            value = record.get("cnn_value_score", 0.5)

            # Create synthetic tile from scores (for transfer learning on scores)
            # In production, pair with actual tile data via input_hash_sha256
            tile = np.random.default_rng(hash(record.get("input_hash_sha256", "")) % 2**32).random(
                (3, 64, 64), dtype=np.float32
            )
            tiles.append(tile)
            scores.append((cloud, anomaly, value))

    print(f"Loaded {len(tiles)} pseudo-labeled samples from audit log {path}")
    return FeedbackDataset(tiles, scores)


# ── Model builder ───────────────────────────────────────────────────────────


def build_model(checkpoint: Path | None = None, in_channels: int = 3) -> nn.Module:
    """Build CloudMaskHead, optionally loading from a checkpoint."""
    from torchvision.models import mobilenet_v3_small, MobileNet_V3_Small_Weights

    class CloudMaskHead(nn.Module):
        def __init__(self, in_ch: int = 3) -> None:
            super().__init__()
            self.input_proj = nn.Sequential(
                nn.Conv2d(in_ch, 3, kernel_size=1, bias=False),
                nn.BatchNorm2d(3),
            ) if in_ch != 3 else nn.Identity()
            backbone = mobilenet_v3_small(weights=MobileNet_V3_Small_Weights.DEFAULT)
            self.features = backbone.features
            self.pool = nn.AdaptiveAvgPool2d(1)
            self.head = nn.Sequential(
                nn.Linear(576, 128), nn.ReLU(), nn.Dropout(0.2),
                nn.Linear(128, 3), nn.Sigmoid(),
            )

        def forward(self, x: torch.Tensor) -> torch.Tensor:
            x = self.input_proj(x)
            x = self.features(x)
            x = self.pool(x).flatten(1)
            return self.head(x)

    model = CloudMaskHead(in_ch=in_channels)

    if checkpoint and checkpoint.exists():
        print(f"Loading checkpoint: {checkpoint}")
        state = torch.load(checkpoint, map_location="cpu", weights_only=True)
        model.load_state_dict(state, strict=False)

    return model


# ── Training loop ───────────────────────────────────────────────────────────


def retrain(
    dataset: FeedbackDataset,
    checkpoint: Path | None = None,
    epochs: int = 10,
    lr: float = 1e-4,
    batch_size: int = 32,
    quick: bool = False,
) -> tuple[Path, float]:
    """Fine-tune the model on feedback data.

    Returns ``(checkpoint_path, best_val_loss)``.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device} | Samples: {len(dataset)} | Epochs: {epochs}")

    if quick:
        subset_size = min(100, len(dataset))
        dataset, _ = random_split(dataset, [subset_size, len(dataset) - subset_size])

    train_size = int(0.8 * len(dataset))
    val_size = len(dataset) - train_size
    train_ds, val_ds = random_split(dataset, [train_size, val_size])

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=batch_size, shuffle=False, num_workers=0)

    model = build_model(checkpoint).to(device)
    criterion = nn.MSELoss()
    # Lower LR for fine-tuning (1/10th of initial training)
    optimizer = optim.AdamW(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_val_loss = float("inf")
    best_path = MODELS_DIR / "cloud_mask_retrained.pt"
    MODELS_DIR.mkdir(parents=True, exist_ok=True)

    for epoch in range(epochs):
        model.train()
        train_loss = 0.0
        for imgs, targets in train_loader:
            imgs, targets = imgs.to(device), targets.to(device)
            optimizer.zero_grad()
            preds = model(imgs)
            loss = criterion(preds, targets)
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * imgs.size(0)
        train_loss /= len(train_ds)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for imgs, targets in val_loader:
                imgs, targets = imgs.to(device), targets.to(device)
                preds = model(imgs)
                val_loss += criterion(preds, targets).item() * imgs.size(0)
        val_loss /= len(val_ds)

        scheduler.step()
        print(f"  Epoch {epoch+1:3d}/{epochs} | train_loss={train_loss:.4f} | val_loss={val_loss:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(model.state_dict(), best_path)

    print(f"Retraining complete. Best val_loss={best_val_loss:.4f}")
    return best_path, best_val_loss


# ── Export ──────────────────────────────────────────────────────────────────


def export_onnx(checkpoint_path: Path) -> Path:
    """Export retrained model to ONNX for deployment."""
    model = build_model(checkpoint_path)
    model.eval()

    onnx_path = MODELS_DIR / "cloud_mask_mobilenet_int8.onnx"
    dummy = torch.randn(1, 3, 64, 64)
    torch.onnx.export(
        model, dummy, str(onnx_path),
        opset_version=17,
        input_names=["input"],
        output_names=["scores"],
        dynamic_axes={
            "input": {0: "batch", 2: "height", 3: "width"},
            "scores": {0: "batch"},
        },
    )
    print(f"ONNX exported: {onnx_path} ({onnx_path.stat().st_size // 1024} KB)")
    return onnx_path


# ── Pipeline orchestrator ───────────────────────────────────────────────────


def run_pipeline(args: argparse.Namespace) -> None:
    """Full retrain → validate → register pipeline."""
    registry = ModelRegistry(MODELS_DIR)
    current = registry.get_active()
    current_loss = current["val_loss"] if current else float("inf")

    print(f"Current active model: {current['version'] if current else 'none'} "
          f"(val_loss={current_loss:.4f})")

    # Load data
    if args.feedback:
        dataset = load_feedback_csv(Path(args.feedback))
    elif args.from_audit:
        dataset = load_audit_log(Path(args.from_audit))
    else:
        sys.exit("ERROR: Provide --feedback CSV or --from-audit JSONL")

    if len(dataset) < 10:
        sys.exit(f"ERROR: Only {len(dataset)} samples — need at least 10 for retraining")

    # Find best existing checkpoint
    checkpoint = None
    if current:
        pt_path = MODELS_DIR / current["filename"].replace(".onnx", ".pt")
        if pt_path.exists():
            checkpoint = pt_path

    # Retrain
    best_path, best_loss = retrain(
        dataset,
        checkpoint=checkpoint,
        epochs=args.epochs,
        lr=args.lr,
        batch_size=args.batch_size,
        quick=args.quick,
    )

    # Compare with current model
    improved = best_loss < current_loss
    print(f"\nComparison: new_val_loss={best_loss:.4f} vs current={current_loss:.4f} "
          f"→ {'IMPROVED' if improved else 'NO IMPROVEMENT'}")

    if args.dry_run:
        print("Dry run — not registering model")
        return

    if not improved and not args.force:
        print("Skipping registration (use --force to override)")
        return

    # Export to ONNX
    onnx_path = export_onnx(best_path)

    # Determine next version
    versions = registry.list_versions()
    if versions:
        last = versions[-1]["version"]
        parts = last.split(".")
        next_ver = f"{parts[0]}.{parts[1]}.{int(parts[2]) + 1}"
    else:
        next_ver = "1.0.0"

    # Register
    entry = registry.register(
        onnx_path,
        version=next_ver,
        dataset=args.feedback or args.from_audit or "unknown",
        epochs=args.epochs,
        val_loss=best_loss,
        metrics={"improvement_pct": round((current_loss - best_loss) / max(current_loss, 1e-6) * 100, 2)},
        notes=f"Retrained {time.strftime('%Y-%m-%d')} from {len(dataset)} samples",
        activate=True,
    )

    print(f"\nRegistered model v{next_ver}")
    print(f"  File: {entry['filename']}")
    print(f"  SHA-256: {entry['sha256'][:32]}…")
    print(f"  Val loss: {best_loss:.4f}")
    print(f"\nDeploy: copy models/{entry['filename']} to Jetson and restart container.")


# ── CLI ─────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Continuous retraining pipeline for edge triage model",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    src = parser.add_mutually_exclusive_group()
    src.add_argument("--feedback", type=str, help="Path to analyst feedback CSV")
    src.add_argument("--from-audit", type=str, help="Path to audit log JSONL")

    parser.add_argument("--epochs", type=int, default=10, help="Fine-tuning epochs (default: 10)")
    parser.add_argument("--lr", type=float, default=1e-4, help="Learning rate (default: 1e-4)")
    parser.add_argument("--batch-size", type=int, default=32, help="Batch size (default: 32)")
    parser.add_argument("--quick", action="store_true", help="Quick run (small subset)")
    parser.add_argument("--dry-run", action="store_true", help="Train but don't register")
    parser.add_argument("--force", action="store_true", help="Register even if metrics don't improve")
    args = parser.parse_args()

    run_pipeline(args)


if __name__ == "__main__":
    main()
